<?php
/**
 * @file
 * Adds the web-trends tracking code to the site.
 */

/**
 * Implements hook_menu().
 */
function ding_kpi_menu() {
  $items = array();

  $items['admin/config/ding/kpi'] = array(
    'title' => 'kpi',
    'description' => 'Settings for the kpi analytics tool.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_kpi_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_kpi.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_page_alter().
 */
function ding_kpi_page_alter(&$page) {
  // Get configuration variables set in the administration interface.
  $domain = variable_get('kpi_domain', FALSE);
  $dcs_id = variable_get('kpi_dcs_id', FALSE);

  // Check that kpi have been configured.
  if (!$domain || !$dcs_id) {
    watchdog('ding_kpi', 'Ding kpi module not configured.', array(), WATCHDOG_NOTICE);
    return;
  }

  // Create custom inline script.
  $script = <<<EOT

window.webtrendsAsyncInit=function(){
    var dcs=new Webtrends.dcs().init({
        dcsid: "$dcs_id",
        domain:"statse.webtrendslive.com",
        timezone:1,
        i18n:true,
        adimpressions:true,
        adsparam:"WT.ac",
        offsite:true,
        download:true,
        downloadtypes:"avi,csv,doc,docx,exe,gzip,mp3,mp4,pdf,ppt,pptx,rar,txt,wav,xls,xlsx,zip",
        fpcdom: ".$domain",
        }).track();

};

(function(){
    var s=document.createElement("script"); s.async=true; s.src="/sites/all/modules/custom/ding_kpi/js/kpi.min.js?na58c";    
    var s2=document.getElementsByTagName("script")[0]; s2.parentNode.insertBefore(s,s2);
}());        

EOT;

function ding_kpi_html_head_alter(&$head_elements) {
    $Query = "";
    $SearchResults = drupal_static('ting_search_results');
    if (strpos($_GET["q"], 'search/ting/') !== FALSE || strpos($_GET["q"], 'search/node/') !== false )
    {
        $Query = explode('/', $_GET["q"]);
        
        if(sizeof($Query)== 3 && $Query[sizeof($Query)-1])
        {
            $Query = $Query[sizeof($Query)-1];
        }
        if(isset($SearchResults->numTotalObjects))
        {
            $SearchCount = strpos($_GET["q"], 'search/ting/') !== FALSE ? $SearchResults->numTotalObjects : "1";
        }
        else
        {
            $SearchCount = "1";
        }
        
        $head_elements['Search_keywords'] = array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array('name' => 'WT.oss', 'content' => $Query ),
          );
          $head_elements['Search_count'] = array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array('name' => 'WT.oss_r', 'content' => $SearchCount),
          );
    }   

}

  drupal_add_js($script, array(
    'type' => 'inline',
    'scope' => 'footer',
    'weight' => 99,
    'cache' => TRUE,
  ));

  // Fallback HTML if JS is not enabled.
  $html = '<noscript>
            <div><img alt="DCSIMG" id="DCSIMG" width="1" height="1" src="//statse.webtrendslive.com/'.$dcs_id.'/njs.gif?dcsuri=/nojavascript&amp;WT.js=No&amp;WT.tv=10.4.1&amp;dcssip='.$domain.'"/></div>
          </noscript>';

  $page['footer']['kpi'] = array(
    '#type' => 'markup',
    '#markup' => $html,
  );
}
